version: '3.8'

services:
  server:
    build:
      context: amazing_api
      dockerfile: amazing_api/Dockerfile
    volumes:
      - ./amazing_api/:/api/
    command: uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - 8000:8000
